// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbocwkskxdopubyyagts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdib2N3a3NreGRvcHVieXlhZ3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODYxOTEsImV4cCI6MjA2MzY2MjE5MX0.H7YqA1keOL5YIMVdTyAPi4U2qGKrZtWYohTZDyxxduo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);